# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

source 'git@106.14.57.231:/data/srv/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'QRCodeScanner' do

# ZXingObjC  3.6.9 的版本 要求系统高于11
pod 'ZXingObjC', '>= 3.6.9'
pod 'libqrencode', '~> 3.4.2'

end

